var devices             = [];
let tsdevices           = [];
var profiles            = [];
var activities          = [];
var config              = {};
var modules             = {};
var scheduledFunctions  = [];
let DeviceModules       = [];
let PluginModules       = [];

exports.devices = devices;
exports.tsdevices = tsdevices;
exports.profiles = profiles;
exports.activities = activities;
exports.config = config;
exports.modules = modules;
exports.scheduledFunctions = scheduledFunctions;
exports.DeviceModules = DeviceModules;
exports.PluginModules = PluginModules;